create table if not exists public.settings (
  id bigint primary key,
  daily_limit numeric not null default 0,
  balance numeric not null default 0,
  monthly_savings_goal numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  amount numeric not null,
  category text not null,
  description text not null default '',
  date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.settings (id, daily_limit, balance, monthly_savings_goal)
values (1, 0, 0, 0)
on conflict (id) do nothing;

create table if not exists public.fuel (
  id bigint generated by default as identity primary key,
  total_amount_spent numeric not null,
  price_per_liter numeric not null,
  liters_filled numeric not null,
  odometer_reading numeric not null,
  mileage numeric,
  cost_per_km numeric,
  date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.savings (
  id bigint generated by default as identity primary key,
  amount numeric not null,
  date date not null,
  note text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
